# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YGUMa2p2JvAGeRJLDoObLvRwzGpTdNHo
"""

def calcular_promedio(lista_numeros):
    """
    Calcula el promedio de una lista de números.

    Parámetros:
    lista_numeros (list): Una lista que contiene números enteros o decimales.

    Retorna:
    float: El promedio de los números en la lista.
           Si la lista está vacía, retorna 0.
    """
    if len(lista_numeros) == 0:
        return 0
    suma_total = sum(lista_numeros)
    cantidad = len(lista_numeros)
    promedio = suma_total / cantidad
    return promedio

# Probando la función
mis_notas = [4.5, 3.8, 5.0, 4.2]
resultado = calcular_promedio(mis_notas)
print("El promedio es:", resultado)